# PopQA Dataset Exploration

**Project:** TrustRAG

**Module:** Dataset Analysis

**Week:** 1

**Objective:**
Understand the structure, quality, and characteristics of the PopQA dataset before building the retrieval pipeline.

In [2]:
import pandas as pd

# Display all columns
pd.set_option("display.max_columns", None)

print("Libraries imported successfully!")

Libraries imported successfully!

In [3]:
df = pd.read_csv("../data/raw/popqa.csv")

print("Dataset loaded successfully!")

Dataset loaded successfully!

In [4]:
print("Shape of Dataset")
print("----------------")
print(f"Rows    : {df.shape[0]}")
print(f"Columns : {df.shape[1]}")

Shape of Dataset
----------------
Rows    : 14267
Columns : 17

In [5]:
df.head()

,id,subj,prop,obj,subj_id,prop_id,obj_id,s_aliases,o_aliases,s_uri,o_uri,s_wiki_title,o_wiki_title,s_pop,o_pop,question,possible_answers
0,4222362,George Rankin,occupation,politician,1850297,22,2834605,"[""George James Rankin""]","[""political leader"",""political figure"",""polit....",http://www.wikidata.org/entity/Q5543720,http://www.wikidata.org/entity/Q82955,George Rankin,Politician,142,25692,What is George Rankin's occupation?,"[""politician"", ""political leader"", ""political ..."
1,4725190,John Mayne,occupation,journalist,2079053,22,663400,[],"[""journo"",""journalists""]",http://www.wikidata.org/entity/Q6247345,http://www.wikidata.org/entity/Q1930187,John Mayne,Journalist,236,24952,What is John Mayne's occupation?,"[""journalist"", ""journo"", ""journalists""]"
2,4382392,Henry Feilden,occupation,politician,1925450,22,2834605,"[""Henry Master Feilden""]","[""political leader"",""political figure"",""polit....",http://www.wikidata.org/entity/Q5725578,http://www.wikidata.org/entity/Q82955,Henry Feilden (Conservative politician),Politician,58,25692,What is Henry Feilden's occupation?,"[""politician"", ""political leader"", ""political ..."
3,4822110,Kathy Saltzman,occupation,politician,2122743,22,2834605,[],"[""political leader"",""political figure"",""polit....",http://www.wikidata.org/entity/Q6377295,http://www.wikidata.org/entity/Q82955,Kathy Saltzman,Politician,127,25692,What is Kathy Saltzman's occupation?,"[""politician"", ""political leader"", ""political ..."
4,4011112,Eleanor Davis,occupation,cartoonist,1752619,22,68412,"[""Eleanor McCutcheon Davis""]","[""graphic artist"",""animator"",""illustrator""]",http://www.wikidata.org/entity/Q5354261,http://www.wikidata.org/entity/Q1114448,Eleanor Davis,Cartoonist,317,9649,What is Eleanor Davis's occupation?,"[""cartoonist"", ""graphic artist"", ""animator"", ""..."

In [6]:
print(df.columns.tolist())

['id', 'subj', 'prop', 'obj', 'subj_id', 'prop_id', 'obj_id', 's_aliases', 'o_aliases', 's_uri', 'o_uri', 's_wiki_title', 'o_wiki_title', 's_pop', 'o_pop', 'question', 'possible_answers']

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 14267 entries, 0 to 14266
Data columns (total 17 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   id                14267 non-null  int64
 1   subj              14264 non-null  str
 2   prop              14267 non-null  str
 3   obj               14267 non-null  str
 4   subj_id           14267 non-null  int64
 5   prop_id           14267 non-null  int64
 6   obj_id            14267 non-null  int64
 7   s_aliases         14267 non-null  str
 8   o_aliases         14267 non-null  str
 9   s_uri             14267 non-null  str
 10  o_uri             14267 non-null  str
 11  s_wiki_title      14267 non-null  str
 12  o_wiki_title      14250 non-null  str
 13  s_pop             14267 non-null  int64
 14  o_pop             14267 non-null  int64
 15  question          14267 non-null  str
 16  possible_answers  14267 non-null  str
dtypes: int64(6), str(11)
memory usage: 5.9 MB

In [8]:
df.isnull().sum()

id                   0
subj                 3
prop                 0
obj                  0
subj_id              0
prop_id              0
obj_id               0
s_aliases            0
o_aliases            0
s_uri                0
o_uri                0
s_wiki_title         0
o_wiki_title        17
s_pop                0
o_pop                0
question             0
possible_answers     0
dtype: int64

In [9]:
duplicates = df["question"].duplicated().sum()

print("Duplicate Questions:", duplicates)

Duplicate Questions: 1199

In [10]:
df["question"].sample(10, random_state=42)

9037             Who was the screenwriter for On the Town?
11153    What is the religion of Juan Soldevilla y Romero?
2701                               What genre is Haddaway?
10870                 Who was the composer of Chances Are?
4342                 Who was the producer of The Pioneers?
9240                Who was the screenwriter for The City?
542                    In what city was Jerrold Katz born?
8899         Who was the screenwriter for Sixteen Candles?
12399                     Who is the author of Revolution?
8204          Who was the screenwriter for The Great Fire?
Name: question, dtype: str

In [11]:
df["possible_answers"].head(10)

0    ["politician", "political leader", "political ...
1              ["journalist", "journo", "journalists"]
2    ["politician", "political leader", "political ...
3    ["politician", "political leader", "political ...
4    ["cartoonist", "graphic artist", "animator", "...
5         ["mathematician", "economist", "economists"]
6    ["talent manager", "artist manager", "band man...
7    ["politician", "political leader", "political ...
8    ["politician", "political leader", "political ...
9          ["actor", "actress", "actors", "actresses"]
Name: possible_answers, dtype: str

In [12]:
df[["s_pop", "o_pop"]].describe()

              s_pop         o_pop
count  1.426700e+04  1.426700e+04
mean   1.889079e+04  9.893237e+04
std    1.904192e+05  2.547495e+05
min    2.000000e+00 -2.000000e+00
25%    2.350000e+02  2.420500e+03
50%    9.750000e+02  1.617000e+04
75%    5.784000e+03  8.055200e+04
max    1.510152e+07  1.629691e+06